sdaemon.py script was downloaed form elsewhere and does not belong to me
